### ISSUE TITLE
Web configuration

### ISSUE THREAD

**Issue by iranzo** [Linutronix/TSN-Testbench#12]
## Description

As it was described in #11  we need to get the github repo to configure the webpage to be served out of a branch 'gh-pages', until then, there will be no webpage available

**Comment by shifty91** [comment]
Yeah, i did that after pushing your commit. The webpage should be available as usual.

**Comment by iranzo** [comment]
Right, now it's working again, I did test when opening the issue and was not yet alive and wanted to make sure it was fine.

TY!
