### ISSUE TITLE
Hardware for multi middleware test

### ISSUE THREAD

**Issue by curious-blackbird** [Linutronix/TSN-Testbench#14]
## Description

when trying to run the multi middleware test with xdp and packet, I get this error:
```
Error: Number of traffic classes is greater than number of HW queues.
```
This is caused by the `tc` command assigning the traffic classes:
https://github.com/Linutronix/TSN-Testbench/blob/75db269af5422064ef361eb144c45ca4a8b90d2b/tests/multi_middleware/xdp/flow_ehl.sh#L69
The used NIC Intel i226-IT only supports 4 queues. As the example uses more traffic classes and queues, what hardware is capable of running this example? The recommended Computers have a I225/I226 NIC with 4 queues.

## Background Information / Reproduction Steps

1. clone the repository
2. build the TSN-Testbench
3. run the test

## Checklist

Please provide the following information:

- [x] Hardware and NIC(s) being used: 
[UPN-EDGE-ADLNI3-A10-1664](https://eu.mouser.com/ProductDetail/AAEON-UP/UPN-EDGE-ADLNI3-A10-1664?qs=Jm2GQyTW%2Fbj%2FT7PR5OosAA%3D%3D) with Intel i226-IT
- [x] Configuration files being used: 
[multi_middleware/xdp](https://github.com/Linutronix/TSN-Testbench/tree/main/tests/multi_middleware/xdp)
- [x] Linux kernel version being used: 
6.1.0-23-rt-amd64
- [x] Linux distribution being used:
Debian GNU/Linux 12 (bookworm)

**Comment by wtedeschi** [comment]
Hello Curious-blackbird,

The test was written for another NIC the integrated TSN on the Intel Atom x6000E socs - you can see in flow the ehl suffix.
They have 8 Rx and 8 Tx  queues.
To make this example to work with i226 you will need to adapt the queues and the usage of the XDP zero copy.
Let me be a bit more verbose:
the XDP demands a queue for itself, once you set one TC to use XDP the assigned queue cannot be used for other TC, it means the some other TCs will not be able to use XDP.

**Comment by shifty91** [comment]
Fred, we should add a multi middle ware example for i226 as well. Let me do that.

**Comment by wtedeschi** [comment]
Makes sense!
In any case an explanation was needed…

**Comment by curious-blackbird** [comment]
What computer do you use to run this testcase? I haven't found one with the needed capabilities.

**Comment by shifty91** [comment]
@curious-blackbird This testcase ran on Congatec SA7 with Intel Atom x6000E processor (https://www.congatec.com/de/produkte/smarc/conga-sa7/) and the Intel EHL CRB.

**Comment by shifty91** [comment]
@curious-blackbird, @wtedeschi I've added the same multi middleware test for i226. Spawns four application instances on each side. The **packet** one using Tx Time on one queue and the **XDP** variant using all four available hardware queues.

Also added `scripts/prepare_config.pl` to easily adjust MAC, IP and interface names in the YAML config files.

For example:
`scripts/prepare_config.pl -a <ref_mac> -b <mirror_mac> -c <ref_ip> -d <mirror_ip> -i <inf_name> tests/multi_middlewar/i226/xdp/*.yaml`
