### ISSUE TITLE
XDP Traffic not working on Elkhart Lake Platforms

### ISSUE THREAD

**Issue by palanrao** [Linutronix/TSN-Testbench#4]
## Description
Used the XDP example provided under "tests/multimiddleware/xdp" to verify XDP traffic on Elkhart Lake platforms connected back to back. 

## Background Information / Reproduction Steps

How can the issue be reproduced?
Update the config files with correct ethernet interface and destination MAD address under the example test, "tests/multimiddleware/xdp". Run mirror.sh on the listener system and ref.sh on the talker system. 

**Note:** AF_PACKET test under "tests/multimiddleware/packet" is working fine on the same test setup. 

## Checklist
Attached the errors reported both by the reference and mirror applications
![test_multi_xdp_ehl_mirror_output](https://github.com/Linutronix/TSN-Testbench/assets/97596357/6c99be3b-0ff8-4013-a48d-14a3da1d75dd)
![test_multi_xdp_ehl_ref_output](https://github.com/Linutronix/TSN-Testbench/assets/97596357/13efd6b8-6e44-4ba6-b7b4-495e540a229b)

Please provide the following information:

 - [ ] Hardware and NIC(s) being used
 Intel Elkhart Lake platforms with XGMAC ethernet interface connected back to back.

 - [ ] Configuration files being used
Used the same configuration files by updating the actual ethernet interface name and destination MAD id's. Executed "tetss/multimiddleware/xdp/mirror.sh" on the listener system and "tetss/multimiddleware/xdp/ref.sh" on the talker system. 

libbpf version  0.7.0
libxdp version 1.2.8
OS: Linux intel-corei7-64 5.15.113-rt64-intel-ese-standard-lts-rt #1 SMP PREEMPT_RT Tue Jun 27 04:38:56 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by shifty91** [comment]
Hi @palanrao,

the issue seems to be that the `libxdp` cannot find the `xdp-dispatcher` eBPF program. However, this program is part of `libxdp`. Furthermore, it is required to run this test.

Can you make sure that libxdp is correctly installed and provides a file called `xdp-dispatcher.o`?

What Linux distribution are you using? For instance, in Debian it works out-of-the-box [1].

[1] - https://packages.debian.org/bookworm/amd64/libxdp1/filelist

**Comment by palanrao** [comment]
Hi @shifty91 and @wtedeschi ,
Elkhart lake platforms are running the Yocto builds meant for those platforms: 
**Linux intel-corei7-64 5.15.113-rt64-intel-ese-standard-lts-rt https://github.com/Linutronix/TSN-Testbench/pull/1 SMP PREEMPT_RT Tue Jun 27 04:38:56 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux**
Do you recommend to install Ubuntu on Elkhart Lake platforms to be able to verify XDP traffic?
Could you share the kernel version, libbpf and libxdp versions on which the XDP traffic was tested on Elkhart Lake platforms?

**Comment by shifty91** [comment]
Hi @palanrao,

looks much better. The problem is ``btf_vmlinux is malformed``. Make sure that your kernel has ``CONFIG_DEBUG_INFO_BTF=y`` set. A clean kernel rebuild afterwards should solve the issue.

In the meantime, I've tested my EHL boards with Debian 12 und Linux v6.1-RT which works fine.

**Comment by shifty91** [comment]
Should be solved by kernel rebuild with BTF info set.
